############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2015 Xilinx Inc. All rights reserved.
############################################################
set_directive_unroll "Taylor_exponential/l3"
set_directive_unroll "Taylor_exponential/l2"
set_directive_unroll "Taylor_exponential/l1"
set_directive_pipeline -II 1 "DOT_exp1/DOT_exp1_label0"
set_directive_unroll "DOT_exp1/DOT_exp1_label1"
set_directive_array_partition -type complete -dim 1 "DOT_exp1" a
set_directive_array_partition -type complete -dim 1 "DOT_exp1" b
set_directive_unroll "DOT_exp1/DOT_exp1_label2"
set_directive_unroll "DOT_exp1/DOT_product"
set_directive_unroll "DOT_exp1/power_loop"
set_directive_unroll "DOT_exp1/Factorial"
set_directive_unroll "DOT_exp1/ADD1_loop"
set_directive_unroll "DOT_exp1/ADD2_loop"
set_directive_unroll "DOT_exp1/ADD3_loop"
set_directive_unroll "DOT_exp1/power_loop2"
set_directive_unroll "DOT_exp1/power_loop8"
set_directive_pipeline -II 1 "wrapped_DOT_matrix/DOT_LOOP"
set_directive_unroll "Normilizer/sum_loop1"
set_directive_inline "Normilizer"
set_directive_unroll "Normilizer/sum_loop2"
set_directive_unroll "Normilizer/Div_loop"
set_directive_pipeline -II 1 "wrapped_DOT_matrix/DOT_LOOP2"
set_directive_pipeline -II 1 "wrapped_DOT_matrix/DOT_LOOP3"
set_directive_pipeline -II 1 "wrapped_DOT_Full_Algorithm/DOT_LOOP"
set_directive_pipeline -II 1 "wrapped_DOT_Full_Algorithm/DOT_LOOP2"
set_directive_pipeline -II 1 "wrapped_DOT_Full_Algorithm/DOT_LOOP3"
set_directive_unroll "SVM/Dif2"
set_directive_unroll "SVM/Dif1"
set_directive_unroll "SVM/Sum2"
set_directive_unroll "SVM/Sum1"
set_directive_unroll "SVM/EXP"
set_directive_unroll "SVM/DOT10"
set_directive_unroll "SVM/ADD_loop1"
set_directive_unroll "EXP16/power_loop2"
set_directive_unroll "EXP16/power_loop"
set_directive_unroll "EXP16/DOT_exp1_label1"
set_directive_unroll "EXP16/ADD1_loop"
set_directive_unroll "EXP16/ADD2_loop"
set_directive_unroll "EXP16/Factorial"
set_directive_array_partition -type complete -dim 2 "SVM" FV
set_directive_array_partition -type complete -dim 1 "SVM" Alpha
set_directive_array_partition -type complete -dim 1 "SVM" Input
set_directive_unroll "SVM_scale/Dif2"
set_directive_unroll "SVM_scale/Dif1"
set_directive_unroll "SVM_scale/Sum2"
set_directive_unroll "SVM_scale/Sum1"
set_directive_unroll "SVM_scale/EXP"
set_directive_unroll "SVM_scale/DOT10"
set_directive_unroll "SVM_scale/ADD_loop1"
set_directive_unroll "SVM_scale/loop_final"
set_directive_unroll "EXP16_linear_reg/Factorial"
set_directive_unroll "EXP16_linear_reg/power_loop2"
set_directive_unroll "EXP16_linear_reg/power_loop"
set_directive_unroll "EXP16_linear_reg/DOT_exp1_label1"
set_directive_unroll "EXP16_linear_reg/ADD1_loop"
set_directive_unroll "EXP16_linear_reg/ADD2_loop"
